project:
  type: website

website:
  title: "Alex Gonzalez"
  site-url: https://alexgonzalezc.dev/
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: linkedin
        href: https://twitter.com
format:
  html:
    theme:
      light: [lux, styles.scss]
      dark: [slate, styles.scss]
    css: styles.css



