name: Deploy Quarto Website To GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Pandoc (for markdown conversion)
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y python3 python3-pip
          pip install -r requirements.txt || true  # optional

      - name: Render Quarto project
        run: quarto render

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ./_site
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
